language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - pip install -U pip setuptools
install:
  - pip install -Ur requirements.txt
  - pip install .
  - python setup.py develop
script:
  - py.test
  - mypy --ignore-missing-imports py_backwards
