language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -U pip
  - python -m pip install -r requirements.txt
  - python -m pip install .
  - python setup.py develop
script:
  - py.test
  - mypy --ignore-missing-imports py_backwards
